linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - goimports
    - revive
    - gosec
    - bodyclose
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
  gosec:
    excludes:
      - G404 # Use of weak random number generator

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - third_party
    - gen
    - frontend
    - node_modules
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: \.d\.go$
      linters:
        - typecheck
    - path: /gen/
      linters:
        - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0
