linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - goimports
    - revive
    - gosec
    - bodyclose
    - gocritic

linters-settings:
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: true
  gosec:
    excludes:
      - G101 # False positive: these are config key names, not actual credentials
      - G115 # Integer overflow conversion - intentional uint32 conversion
      - G404 # Use of weak random number generator

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - third_party
    - gen
    - frontend
    - node_modules
    - mocks
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: \.d\.go$
      linters:
        - typecheck
    - path: /gen/
      linters:
        - typecheck
    # Exclude stuttering name warnings - changing these would break existing imports
    - linters:
        - revive
      text: "stutters"
  max-issues-per-linter: 0
  max-same-issues: 0
