# mockery configuration
# Run `mockery` in project root to generate mocks
# Documentation: https://vektra.github.io/mockery/

with-expecter: true
dir: "mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"

# Fix deprecation warnings for v3 compatibility
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/hoangdaochuz/ecommerce-microservice-golang/apps/order/repository:
    interfaces:
      OrderRepositoryInterface:
  github.com/hoangdaochuz/ecommerce-microservice-golang/apps/order/services/order:
    interfaces:
      OrderServiceInterface:
  github.com/hoangdaochuz/ecommerce-microservice-golang/apps/auth/services/auth:
    interfaces:
      AuthServiceInterface:
  github.com/hoangdaochuz/ecommerce-microservice-golang/pkg/cache:
    interfaces:
      Cache:
