version: 3

tasks:
  backend:codegen:
    desc: Generate Go code from proto file
    vars:
      PROTO_FILE: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "Generating from {{.PROTO_FILE}}"

        SERVICE_DIR=$(echo {{.PROTO_FILE}} | cut -d'/' -f2)
        FILE_NAME=$(basename {{.PROTO_FILE}} .proto)
        OUT_DIR="apps/$SERVICE_DIR/api/$FILE_NAME"

        mkdir -p "$OUT_DIR"

        protoc \
          --proto_path=$(dirname {{.PROTO_FILE}}) \
          --go_out="$OUT_DIR" --go_opt=paths=source_relative \
          --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
          {{.PROTO_FILE}}
