version: 3

dotenv: [".env"]

tasks:
  backend:codegen:
    desc: Generate Go code from proto file
    vars:
      PROTO_FILE: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "Generating from {{.PROTO_FILE}}"

        SERVICE_DIR=$(echo {{.PROTO_FILE}} | cut -d'/' -f2)
        FILE_NAME=$(basename {{.PROTO_FILE}} .proto)
        OUT_DIR="apps/$SERVICE_DIR/api/$FILE_NAME"

        mkdir -p "$OUT_DIR"

        protoc \
          --proto_path=$(dirname {{.PROTO_FILE}}) \
          --go_out="$OUT_DIR" --go_opt=paths=source_relative \
          --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
          {{.PROTO_FILE}}

  backend:codegen:dgo:
    desc: Generate .d.go file from proto file
    vars:
      PROTO_FILE: "{{.CLI_ARGS}}"
      OUT_FILE: '{{.OUT_FILE | default ""}}'
    cmds:
      - |
        if [ -z "{{.PROTO_FILE}}" ]; then
          echo "Error: Please provide proto file path"
          echo "Usage: task backend:codegen:dgo -- apps/order/proto/order.proto [OUT_FILE=path/to/output.d.go]"
          exit 1
        fi
        echo "Generating .d.go from {{.PROTO_FILE}}"

        if [ -n "{{.OUT_FILE}}" ]; then
          OUT_FILE="{{.OUT_FILE}}"
          echo "Using user-specified output file: $OUT_FILE"
        else
          SERVICE_DIR=$(echo {{.PROTO_FILE}} | cut -d'/' -f2)
          FILE_NAME=$(basename {{.PROTO_FILE}} .proto)
          OUT_FILE="apps/$SERVICE_DIR/api/$FILE_NAME/$FILE_NAME.d.go"
          echo "Using default output file: $OUT_FILE"
        fi

        # Create output directory if it doesn't exist
        mkdir -p "$(dirname "$OUT_FILE")"

        go run pkg/codegen/cli/main.go -type=backend-contract -protofilePath={{.PROTO_FILE}} -dgoOutput="$OUT_FILE"
        echo "Generated: $OUT_FILE"

  frontend:codegen:service:
    desc: Generate TypeScript/React Query code frontend for specific service
    vars:
      outdir: '{{.outdir | default "./frontend/apis"}}'
      service: '{{.service | default "api-client"}}'
    cmds:
      - |
        echo "  ðŸ“ Output Directory: {{.outdir}}"
        echo "  ðŸ“¦ Service Name: {{.service}}"
        echo "ðŸ”„ Generating frontend code..."
        go run pkg/codegen/cli/main.go -outdir="{{.outdir}}" -service="{{.service}}"
  frontend:codegen:all:
    desc: Generate TypeScript/React Query code frontend for all services
    vars:
      outdir: '{{.outdir | default "./frontend/apis"}}'
    cmds:
      - |
        echo "  ðŸ“ Output Directory: {{.outdir}}"
        echo "ðŸ”„ Generating frontend code..."
        go run pkg/codegen/cli/main.go -outdir="{{.outdir}}"
  frontend:codegen:help:
    desc: Show help for frontend code generation
    cmds:
      - |
        echo "Frontend Code Generator Help"
        echo "============================"
        echo ""
        echo ""
        echo "Basic usage:"
        echo "  task frontend:codegen outdir=./my-frontend/api service=my-api"
        echo ""
        echo "Available parameters:"
        echo "  outdir  - Output directory (default: ./frontend/apis)"
        echo "  service - Service name for generated code (default: api-client)"
        echo ""
        echo "Examples:"
        echo "  task frontend:codegen service=ecommerce-api outdir=./frontend/generated"

  backend:build:nats_auth:
    desc: Build docker image for nats auth service
    vars:
      IMAGE: "{{.DOCKER_USERNAME}}/nats_auth"
      TAG: "0.1.45"
    cmds:
      - |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build --no-cache  -f apps/nats_auth/Dockerfile -t {{.IMAGE}}:{{.TAG}} .
        docker push {{.IMAGE}}:{{.TAG}}

  backend:dev:
    desc: Run backend development server
    cmds:
      - rm -f pid.txt *.log
      - echo "# Backend Services PIDs" > pid.txt
      - task: go_apps

  go_apps:
    deps:
      - task: backend:api_gateway
        on_success: backend:authenticate
      - task: backend:authenticate
        on_success: backend:order
      - task: backend:order
  backend:api_gateway:
    desc: Run api gateway service
    cmds:
      - |
        go build -o cmd/main cmd/main.go
        echo "Starting API Gateway..."
        ./cmd/main 2>&1 | tee -a logs/api_gateway.log &
        sleep 1
        API_PID=$(pgrep -f "^./cmd/main$")
        echo "api_gateway:$API_PID" >> pid.txt
        echo "API Gateway started with PID: $API_PID"
        wait
  backend:order:
    desc: Run order service
    cmds:
      - |
        go build -o apps/order/cmd/main apps/order/cmd/main.go
        echo "Starting Order service..."
        ./apps/order/cmd/main 2>&1 | tee -a logs/order.log &
        sleep 1
        ORDER_PID=$(pgrep -f "^./apps/order/cmd/main$")
        echo "order:$ORDER_PID" >> pid.txt
        echo "Order service started with PID: $ORDER_PID"
        wait
  backend:authenticate:
    desc: Run authenticate service
    cmds:
      - |
        go build -o apps/auth/cmd/main apps/auth/cmd/main.go
        echo "Starting authenticate service..."
        ./apps/auth/cmd/main 2>&1 | tee -a logs/auth.log &
        sleep 1
        AUTH_PID=$(pgrep -f "^./apps/auth/cmd/main$")
        echo "auth:$AUTH_PID" >> pid.txt
        echo "Auth service started with PID: $AUTH_PID"
        wait

  # ==================== Testing Tasks ====================

  test:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    desc: Run unit tests only
    cmds:
      - |
        echo "Running unit tests..."
        go test -v -race -short \
          ./api_gateway/... \
          ./apps/order/... \
          ./apps/auth/... \
          ./pkg/... \
          ./testutil/... \
          2>&1 | tee test-unit-output.txt
        echo "Unit tests completed!"

  test:integration:
    desc: Run integration tests (requires infrastructure)
    cmds:
      - |
        echo "Running integration tests..."
        go test -v -race -tags=integration \
          ./api_gateway/... \
          ./apps/order/... \
          ./apps/auth/... \
          2>&1 | tee test-integration-output.txt
        echo "Integration tests completed!"

  test:e2e:
    desc: Run end-to-end tests (requires running services)
    vars:
      API_URL: '{{.API_URL | default "http://localhost:8080"}}'
    cmds:
      - |
        echo "Running E2E tests against {{.API_URL}}..."
        E2E_API_GATEWAY_URL={{.API_URL}} go test -v -tags=e2e ./e2e/... -timeout 5m
        echo "E2E tests completed!"

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - |
        echo "Running tests with coverage..."
        go test -v -race -coverprofile=coverage.out -covermode=atomic \
          ./api_gateway/... \
          ./apps/order/... \
          ./apps/auth/... \
          ./pkg/... \
          ./testutil/...

        echo ""
        echo "Coverage Summary:"
        go tool cover -func=coverage.out | tail -20

        echo ""
        echo "Generating HTML coverage report..."
        go tool cover -html=coverage.out -o coverage.html
        echo "Coverage report saved to coverage.html"

  test:coverage:view:
    desc: Open coverage report in browser
    deps: [test:coverage]
    cmds:
      - |
        if command -v open &> /dev/null; then
          open coverage.html
        elif command -v xdg-open &> /dev/null; then
          xdg-open coverage.html
        else
          echo "Please open coverage.html in your browser"
        fi

  test:watch:
    desc: Watch for changes and run tests
    cmds:
      - |
        if ! command -v watchexec &> /dev/null; then
          echo "watchexec not found. Install with: brew install watchexec"
          exit 1
        fi
        watchexec -e go -- go test -short ./...

  # ==================== Mock Generation Tasks ====================

  mocks:generate:
    desc: Generate mocks using Mockery
    cmds:
      - |
        echo "Checking for mockery..."
        if ! command -v mockery &> /dev/null; then
          echo "Installing mockery..."
          go install github.com/vektra/mockery/v2@latest
        fi

        echo "Generating mocks..."
        mockery
        echo "Mocks generated successfully!"

  mocks:clean:
    desc: Clean generated mocks
    cmds:
      - |
        echo "Cleaning mocks directory..."
        rm -rf mocks/
        echo "Mocks cleaned!"

  mocks:regenerate:
    desc: Clean and regenerate all mocks
    cmds:
      - task: mocks:clean
      - task: mocks:generate

  # ==================== Test Help ====================

  test:help:
    desc: Show help for testing tasks
    cmds:
      - |
        echo "Testing Tasks"
        echo "============="
        echo ""
        echo "Available tasks:"
        echo "  task test              - Run all tests (unit + integration)"
        echo "  task test:unit         - Run unit tests only (fast)"
        echo "  task test:integration  - Run integration tests (requires infra)"
        echo "  task test:e2e          - Run E2E tests (requires running services)"
        echo "  task test:coverage     - Generate coverage report"
        echo "  task test:coverage:view - Open coverage report in browser"
        echo "  task test:watch        - Watch for changes and run tests"
        echo ""
        echo "Mock Generation:"
        echo "  task mocks:generate    - Generate mocks using Mockery"
        echo "  task mocks:clean       - Clean generated mocks"
        echo "  task mocks:regenerate  - Clean and regenerate all mocks"
        echo ""
        echo "Examples:"
        echo "  task test:unit                          # Quick feedback during development"
        echo "  task test:coverage                      # Check coverage before PR"
        echo "  task test:e2e API_URL=http://staging:8080  # Run E2E against staging"
