// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationEnpointError int32

const (
	AuthorizationEnpointError_invalid_request           AuthorizationEnpointError = 0
	AuthorizationEnpointError_invalid_scope             AuthorizationEnpointError = 1
	AuthorizationEnpointError_unauthorized_client       AuthorizationEnpointError = 2
	AuthorizationEnpointError_unsupported_response_type AuthorizationEnpointError = 3
	AuthorizationEnpointError_server_error              AuthorizationEnpointError = 4
	AuthorizationEnpointError_interaction_required      AuthorizationEnpointError = 5
	AuthorizationEnpointError_login_required            AuthorizationEnpointError = 6
)

// Enum value maps for AuthorizationEnpointError.
var (
	AuthorizationEnpointError_name = map[int32]string{
		0: "invalid_request",
		1: "invalid_scope",
		2: "unauthorized_client",
		3: "unsupported_response_type",
		4: "server_error",
		5: "interaction_required",
		6: "login_required",
	}
	AuthorizationEnpointError_value = map[string]int32{
		"invalid_request":           0,
		"invalid_scope":             1,
		"unauthorized_client":       2,
		"unsupported_response_type": 3,
		"server_error":              4,
		"interaction_required":      5,
		"login_required":            6,
	}
)

func (x AuthorizationEnpointError) Enum() *AuthorizationEnpointError {
	p := new(AuthorizationEnpointError)
	*p = x
	return p
}

func (x AuthorizationEnpointError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationEnpointError) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_proto_enumTypes[0].Descriptor()
}

func (AuthorizationEnpointError) Type() protoreflect.EnumType {
	return &file_auth_proto_enumTypes[0]
}

func (x AuthorizationEnpointError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationEnpointError.Descriptor instead.
func (AuthorizationEnpointError) EnumDescriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	RedirectURL   string                 `protobuf:"bytes,2,opt,name=RedirectURL,proto3" json:"RedirectURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RedirectResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *RedirectResponse) GetRedirectURL() string {
	if x != nil {
		return x.RedirectURL
	}
	return ""
}

type CallbackRequest struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Code             string                    `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	State            string                    `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	Error            AuthorizationEnpointError `protobuf:"varint,3,opt,name=Error,proto3,enum=auth.AuthorizationEnpointError" json:"Error,omitempty"`
	ErrorDescription string                    `protobuf:"bytes,4,opt,name=ErrorDescription,proto3" json:"ErrorDescription,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CallbackRequest) GetError() AuthorizationEnpointError {
	if x != nil {
		return x.Error
	}
	return AuthorizationEnpointError_invalid_request
}

func (x *CallbackRequest) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

type CallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CallbackResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"` // return other info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetMyProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyProfileResponse) Reset() {
	*x = GetMyProfileResponse{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyProfileResponse) ProtoMessage() {}

func (x *GetMyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyProfileResponse.ProtoReflect.Descriptor instead.
func (*GetMyProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMyProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMyProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetMyProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetMyProfileResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"*\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\"R\n" +
	"\x10RedirectResponse\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\x12 \n" +
	"\vRedirectURL\x18\x02 \x01(\tR\vRedirectURL\"\x9e\x01\n" +
	"\x0fCallbackRequest\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\x125\n" +
	"\x05Error\x18\x03 \x01(\x0e2\x1f.auth.AuthorizationEnpointErrorR\x05Error\x12*\n" +
	"\x10ErrorDescription\x18\x04 \x01(\tR\x10ErrorDescription\"0\n" +
	"\x10CallbackResponse\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"1\n" +
	"\x15ValidateTokenResponse\x12\x18\n" +
	"\aIsValid\x18\x01 \x01(\bR\aIsValid\"\x9a\x01\n" +
	"\x14GetMyProfileResponse\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\x12\x1c\n" +
	"\tFirstName\x18\x03 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x04 \x01(\tR\bLastName\x12\x16\n" +
	"\x06Gender\x18\x05 \x01(\tR\x06Gender\"\x0e\n" +
	"\fEmptyRequest\".\n" +
	"\x0eLogoutResponse\x12\x1c\n" +
	"\tIsSuccess\x18\x01 \x01(\bR\tIsSuccess*\xbb\x01\n" +
	"\x19AuthorizationEnpointError\x12\x13\n" +
	"\x0finvalid_request\x10\x00\x12\x11\n" +
	"\rinvalid_scope\x10\x01\x12\x17\n" +
	"\x13unauthorized_client\x10\x02\x12\x1d\n" +
	"\x19unsupported_response_type\x10\x03\x12\x10\n" +
	"\fserver_error\x10\x04\x12\x18\n" +
	"\x14interaction_required\x10\x05\x12\x12\n" +
	"\x0elogin_required\x10\x062\xc5\x02\n" +
	"\x13AuthenticateService\x123\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x16.auth.RedirectResponse\x129\n" +
	"\bCallback\x12\x15.auth.CallbackRequest\x1a\x16.auth.CallbackResponse\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12>\n" +
	"\fGetMyProfile\x12\x12.auth.EmptyRequest\x1a\x1a.auth.GetMyProfileResponse\x124\n" +
	"\x06Logout\x12\x12.auth.EmptyRequest\x1a\x16.auth.RedirectResponseB\x0fZ\rauth/api/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auth_proto_goTypes = []any{
	(AuthorizationEnpointError)(0), // 0: auth.AuthorizationEnpointError
	(*LoginRequest)(nil),           // 1: auth.LoginRequest
	(*RedirectResponse)(nil),       // 2: auth.RedirectResponse
	(*CallbackRequest)(nil),        // 3: auth.CallbackRequest
	(*CallbackResponse)(nil),       // 4: auth.CallbackResponse
	(*ValidateTokenRequest)(nil),   // 5: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 6: auth.ValidateTokenResponse
	(*GetMyProfileResponse)(nil),   // 7: auth.GetMyProfileResponse
	(*EmptyRequest)(nil),           // 8: auth.EmptyRequest
	(*LogoutResponse)(nil),         // 9: auth.LogoutResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.CallbackRequest.Error:type_name -> auth.AuthorizationEnpointError
	1, // 1: auth.AuthenticateService.Login:input_type -> auth.LoginRequest
	3, // 2: auth.AuthenticateService.Callback:input_type -> auth.CallbackRequest
	5, // 3: auth.AuthenticateService.ValidateToken:input_type -> auth.ValidateTokenRequest
	8, // 4: auth.AuthenticateService.GetMyProfile:input_type -> auth.EmptyRequest
	8, // 5: auth.AuthenticateService.Logout:input_type -> auth.EmptyRequest
	2, // 6: auth.AuthenticateService.Login:output_type -> auth.RedirectResponse
	4, // 7: auth.AuthenticateService.Callback:output_type -> auth.CallbackResponse
	6, // 8: auth.AuthenticateService.ValidateToken:output_type -> auth.ValidateTokenResponse
	7, // 9: auth.AuthenticateService.GetMyProfile:output_type -> auth.GetMyProfileResponse
	2, // 10: auth.AuthenticateService.Logout:output_type -> auth.RedirectResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		EnumInfos:         file_auth_proto_enumTypes,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
